# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  code-quality:
    name: Run Checkstyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run checkstyle scan
        run: mvn -B verify checkstyle:check

  spotbugs:
    name: Run SpotBugs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
     - name: Run checkstyle scan
        run: mvn -B spotbugs:spotbugs
     - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          path: target/spotbugsXml.xml
          name: SpotBugs report


  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Liflecicle Package
        run: mvn -B package --file pom.xml
      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          path: target/InvasioneAliena-1.0-SNAPSHOT.jar
          name: InvasioneAliena1.0
